version: '3.8'

services:
  api:
    build: .
    container_name: nitigrow-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/nitigrow
      - REDIS_URL=redis://redis:6379
      - RUN_WORKER=false
    depends_on:
      - mongo
      - redis
    restart: always

  worker:
    build: .
    container_name: nitigrow-worker
    command: ["node", "src/worker.js"]
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/nitigrow
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:7.0
    container_name: nitigrow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: nitigrow-redis
    ports:
      - "6379:6379"
    restart: always

  minio:
    image: minio/minio
    container_name: nitigrow-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=nitigrow
      - MINIO_ROOT_PASSWORD=supersecret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  mongo_data:
  minio_data:
